version: '3'
services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: confrec
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file: ./backend/.env.example
    depends_on:
      - db
    ports:
      - "8000:8000"

  scraper:
    build: ./backend
    command: bash -c "while true; do python -m app.scraper_runner; sleep 3600; done"
    env_file: ./backend/.env.example
    depends_on:
      - db
      